import type { Status } from '@/types/status';

export const MOCK_STATUSES: Status[] = [
  {
    id: 'mock-bar-1',
    authorId: 'mock-author-1',
    authorName: 'Camille',
    authorSchool: 'ESEO',
    content: 'Qui pour une bière ce soir place du Ralliement ?',
    category: 'bar',
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    isMine: false,
  },
  {
    id: 'mock-bar-2',
    authorId: 'mock-author-2',
    authorName: 'Lucas',
    authorSchool: "Université d'Angers",
    content: 'Apéro sur les quais, tout le monde est le bienvenu !',
    category: 'bar',
    createdAt: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
    isMine: false,
  },
  {
    id: 'mock-sport-1',
    authorId: 'mock-author-3',
    authorName: 'Manon',
    authorSchool: 'ESSCA',
    content: 'Match de foot improvisé au parc de Balzac, venez nombreux !',
    category: 'sport',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    isMine: false,
  },
  {
    id: 'mock-sport-2',
    authorId: 'mock-author-4',
    authorName: 'Hugo',
    authorSchool: "Université d'Angers",
    content: 'Footing autour du lac de Maine ce soir, qui embarque ?',
    category: 'sport',
    createdAt: new Date(Date.now() - 150 * 60 * 1000).toISOString(),
    isMine: false,
  },
  {
    id: 'mock-etude-1',
    authorId: 'mock-author-5',
    authorName: 'Chloé',
    authorSchool: 'UCO Angers',
    content: 'Session révisions à la BU, motivation collective bienvenue.',
    category: 'etude',
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    isMine: false,
  },
  {
    id: 'mock-etude-2',
    authorId: 'mock-author-6',
    authorName: 'Nathan',
    authorSchool: 'ESAIP',
    content: "Qui veut réviser le partiel de demain autour d'un café ?",
    category: 'etude',
    createdAt: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
    isMine: false,
  },
];
